with-expecter: true
resolve-type-alias: false
issue-845-fix: true
outpkg: mocks
all: true

packages:
  github.com/nathakusuma/astungkara/domain/contract:
    interfaces:
      include: ["*"]
    config:
      filename: "{{.InterfaceName}}_mock.go"
      dir: "test/unit/mocks/app"

  github.com/nathakusuma/astungkara/pkg/bcrypt:
    interfaces:
      include: ["*"]
    config:
      filename: "{{.InterfaceName}}_mock.go"
      dir: "test/unit/mocks/pkg"

  github.com/nathakusuma/astungkara/pkg/jwt:
    interfaces:
      include: [ "*" ]
    config:
      filename: "{{.InterfaceName}}_mock.go"
      dir: "test/unit/mocks/pkg"

  github.com/nathakusuma/astungkara/pkg/mail:
    interfaces:
      include: [ "*" ]
    config:
      filename: "{{.InterfaceName}}_mock.go"
      dir: "test/unit/mocks/pkg"

  github.com/nathakusuma/astungkara/pkg/uuidpkg:
    interfaces:
      include: ["*"]
    config:
      filename: "{{.InterfaceName}}_mock.go"
      dir: "test/unit/mocks/pkg"
