// Code generated by mockery v2.51.0. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/nathakusuma/astungkara/domain/dto"

	mock "github.com/stretchr/testify/mock"
)

// MockIAuthService is an autogenerated mock type for the IAuthService type
type MockIAuthService struct {
	mock.Mock
}

type MockIAuthService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIAuthService) EXPECT() *MockIAuthService_Expecter {
	return &MockIAuthService_Expecter{mock: &_m.Mock}
}

// CheckOTPRegisterUser provides a mock function with given fields: ctx, email, otp
func (_m *MockIAuthService) CheckOTPRegisterUser(ctx context.Context, email string, otp string) error {
	ret := _m.Called(ctx, email, otp)

	if len(ret) == 0 {
		panic("no return value specified for CheckOTPRegisterUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, email, otp)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIAuthService_CheckOTPRegisterUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckOTPRegisterUser'
type MockIAuthService_CheckOTPRegisterUser_Call struct {
	*mock.Call
}

// CheckOTPRegisterUser is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - otp string
func (_e *MockIAuthService_Expecter) CheckOTPRegisterUser(ctx interface{}, email interface{}, otp interface{}) *MockIAuthService_CheckOTPRegisterUser_Call {
	return &MockIAuthService_CheckOTPRegisterUser_Call{Call: _e.mock.On("CheckOTPRegisterUser", ctx, email, otp)}
}

func (_c *MockIAuthService_CheckOTPRegisterUser_Call) Run(run func(ctx context.Context, email string, otp string)) *MockIAuthService_CheckOTPRegisterUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockIAuthService_CheckOTPRegisterUser_Call) Return(_a0 error) *MockIAuthService_CheckOTPRegisterUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIAuthService_CheckOTPRegisterUser_Call) RunAndReturn(run func(context.Context, string, string) error) *MockIAuthService_CheckOTPRegisterUser_Call {
	_c.Call.Return(run)
	return _c
}

// LoginUser provides a mock function with given fields: ctx, req
func (_m *MockIAuthService) LoginUser(ctx context.Context, req dto.LoginUserRequest) (dto.LoginResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for LoginUser")
	}

	var r0 dto.LoginResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.LoginUserRequest) (dto.LoginResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.LoginUserRequest) dto.LoginResponse); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(dto.LoginResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.LoginUserRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIAuthService_LoginUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoginUser'
type MockIAuthService_LoginUser_Call struct {
	*mock.Call
}

// LoginUser is a helper method to define mock.On call
//   - ctx context.Context
//   - req dto.LoginUserRequest
func (_e *MockIAuthService_Expecter) LoginUser(ctx interface{}, req interface{}) *MockIAuthService_LoginUser_Call {
	return &MockIAuthService_LoginUser_Call{Call: _e.mock.On("LoginUser", ctx, req)}
}

func (_c *MockIAuthService_LoginUser_Call) Run(run func(ctx context.Context, req dto.LoginUserRequest)) *MockIAuthService_LoginUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(dto.LoginUserRequest))
	})
	return _c
}

func (_c *MockIAuthService_LoginUser_Call) Return(_a0 dto.LoginResponse, _a1 error) *MockIAuthService_LoginUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIAuthService_LoginUser_Call) RunAndReturn(run func(context.Context, dto.LoginUserRequest) (dto.LoginResponse, error)) *MockIAuthService_LoginUser_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterUser provides a mock function with given fields: ctx, req
func (_m *MockIAuthService) RegisterUser(ctx context.Context, req dto.RegisterUserRequest) (dto.LoginResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for RegisterUser")
	}

	var r0 dto.LoginResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.RegisterUserRequest) (dto.LoginResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.RegisterUserRequest) dto.LoginResponse); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(dto.LoginResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.RegisterUserRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIAuthService_RegisterUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterUser'
type MockIAuthService_RegisterUser_Call struct {
	*mock.Call
}

// RegisterUser is a helper method to define mock.On call
//   - ctx context.Context
//   - req dto.RegisterUserRequest
func (_e *MockIAuthService_Expecter) RegisterUser(ctx interface{}, req interface{}) *MockIAuthService_RegisterUser_Call {
	return &MockIAuthService_RegisterUser_Call{Call: _e.mock.On("RegisterUser", ctx, req)}
}

func (_c *MockIAuthService_RegisterUser_Call) Run(run func(ctx context.Context, req dto.RegisterUserRequest)) *MockIAuthService_RegisterUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(dto.RegisterUserRequest))
	})
	return _c
}

func (_c *MockIAuthService_RegisterUser_Call) Return(_a0 dto.LoginResponse, _a1 error) *MockIAuthService_RegisterUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIAuthService_RegisterUser_Call) RunAndReturn(run func(context.Context, dto.RegisterUserRequest) (dto.LoginResponse, error)) *MockIAuthService_RegisterUser_Call {
	_c.Call.Return(run)
	return _c
}

// RequestOTPRegisterUser provides a mock function with given fields: ctx, email
func (_m *MockIAuthService) RequestOTPRegisterUser(ctx context.Context, email string) error {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for RequestOTPRegisterUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIAuthService_RequestOTPRegisterUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequestOTPRegisterUser'
type MockIAuthService_RequestOTPRegisterUser_Call struct {
	*mock.Call
}

// RequestOTPRegisterUser is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockIAuthService_Expecter) RequestOTPRegisterUser(ctx interface{}, email interface{}) *MockIAuthService_RequestOTPRegisterUser_Call {
	return &MockIAuthService_RequestOTPRegisterUser_Call{Call: _e.mock.On("RequestOTPRegisterUser", ctx, email)}
}

func (_c *MockIAuthService_RequestOTPRegisterUser_Call) Run(run func(ctx context.Context, email string)) *MockIAuthService_RequestOTPRegisterUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockIAuthService_RequestOTPRegisterUser_Call) Return(_a0 error) *MockIAuthService_RequestOTPRegisterUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIAuthService_RequestOTPRegisterUser_Call) RunAndReturn(run func(context.Context, string) error) *MockIAuthService_RequestOTPRegisterUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIAuthService creates a new instance of MockIAuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIAuthService {
	mock := &MockIAuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
