// Code generated by mockery v2.51.0. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/nathakusuma/astungkara/domain/dto"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockIFeedbackService is an autogenerated mock type for the IFeedbackService type
type MockIFeedbackService struct {
	mock.Mock
}

type MockIFeedbackService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIFeedbackService) EXPECT() *MockIFeedbackService_Expecter {
	return &MockIFeedbackService_Expecter{mock: &_m.Mock}
}

// CreateFeedback provides a mock function with given fields: ctx, userID, conferenceID, comment
func (_m *MockIFeedbackService) CreateFeedback(ctx context.Context, userID uuid.UUID, conferenceID uuid.UUID, comment string) (uuid.UUID, error) {
	ret := _m.Called(ctx, userID, conferenceID, comment)

	if len(ret) == 0 {
		panic("no return value specified for CreateFeedback")
	}

	var r0 uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string) (uuid.UUID, error)); ok {
		return rf(ctx, userID, conferenceID, comment)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string) uuid.UUID); ok {
		r0 = rf(ctx, userID, conferenceID, comment)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, string) error); ok {
		r1 = rf(ctx, userID, conferenceID, comment)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIFeedbackService_CreateFeedback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateFeedback'
type MockIFeedbackService_CreateFeedback_Call struct {
	*mock.Call
}

// CreateFeedback is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - conferenceID uuid.UUID
//   - comment string
func (_e *MockIFeedbackService_Expecter) CreateFeedback(ctx interface{}, userID interface{}, conferenceID interface{}, comment interface{}) *MockIFeedbackService_CreateFeedback_Call {
	return &MockIFeedbackService_CreateFeedback_Call{Call: _e.mock.On("CreateFeedback", ctx, userID, conferenceID, comment)}
}

func (_c *MockIFeedbackService_CreateFeedback_Call) Run(run func(ctx context.Context, userID uuid.UUID, conferenceID uuid.UUID, comment string)) *MockIFeedbackService_CreateFeedback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(string))
	})
	return _c
}

func (_c *MockIFeedbackService_CreateFeedback_Call) Return(_a0 uuid.UUID, _a1 error) *MockIFeedbackService_CreateFeedback_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIFeedbackService_CreateFeedback_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, string) (uuid.UUID, error)) *MockIFeedbackService_CreateFeedback_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteFeedback provides a mock function with given fields: ctx, id
func (_m *MockIFeedbackService) DeleteFeedback(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteFeedback")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIFeedbackService_DeleteFeedback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteFeedback'
type MockIFeedbackService_DeleteFeedback_Call struct {
	*mock.Call
}

// DeleteFeedback is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockIFeedbackService_Expecter) DeleteFeedback(ctx interface{}, id interface{}) *MockIFeedbackService_DeleteFeedback_Call {
	return &MockIFeedbackService_DeleteFeedback_Call{Call: _e.mock.On("DeleteFeedback", ctx, id)}
}

func (_c *MockIFeedbackService_DeleteFeedback_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockIFeedbackService_DeleteFeedback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockIFeedbackService_DeleteFeedback_Call) Return(_a0 error) *MockIFeedbackService_DeleteFeedback_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIFeedbackService_DeleteFeedback_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockIFeedbackService_DeleteFeedback_Call {
	_c.Call.Return(run)
	return _c
}

// GetFeedbacksByConferenceID provides a mock function with given fields: ctx, conferenceID, lazyReq
func (_m *MockIFeedbackService) GetFeedbacksByConferenceID(ctx context.Context, conferenceID uuid.UUID, lazyReq dto.LazyLoadQuery) ([]dto.FeedbackResponse, dto.LazyLoadResponse, error) {
	ret := _m.Called(ctx, conferenceID, lazyReq)

	if len(ret) == 0 {
		panic("no return value specified for GetFeedbacksByConferenceID")
	}

	var r0 []dto.FeedbackResponse
	var r1 dto.LazyLoadResponse
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, dto.LazyLoadQuery) ([]dto.FeedbackResponse, dto.LazyLoadResponse, error)); ok {
		return rf(ctx, conferenceID, lazyReq)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, dto.LazyLoadQuery) []dto.FeedbackResponse); ok {
		r0 = rf(ctx, conferenceID, lazyReq)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.FeedbackResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, dto.LazyLoadQuery) dto.LazyLoadResponse); ok {
		r1 = rf(ctx, conferenceID, lazyReq)
	} else {
		r1 = ret.Get(1).(dto.LazyLoadResponse)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, dto.LazyLoadQuery) error); ok {
		r2 = rf(ctx, conferenceID, lazyReq)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockIFeedbackService_GetFeedbacksByConferenceID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFeedbacksByConferenceID'
type MockIFeedbackService_GetFeedbacksByConferenceID_Call struct {
	*mock.Call
}

// GetFeedbacksByConferenceID is a helper method to define mock.On call
//   - ctx context.Context
//   - conferenceID uuid.UUID
//   - lazyReq dto.LazyLoadQuery
func (_e *MockIFeedbackService_Expecter) GetFeedbacksByConferenceID(ctx interface{}, conferenceID interface{}, lazyReq interface{}) *MockIFeedbackService_GetFeedbacksByConferenceID_Call {
	return &MockIFeedbackService_GetFeedbacksByConferenceID_Call{Call: _e.mock.On("GetFeedbacksByConferenceID", ctx, conferenceID, lazyReq)}
}

func (_c *MockIFeedbackService_GetFeedbacksByConferenceID_Call) Run(run func(ctx context.Context, conferenceID uuid.UUID, lazyReq dto.LazyLoadQuery)) *MockIFeedbackService_GetFeedbacksByConferenceID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(dto.LazyLoadQuery))
	})
	return _c
}

func (_c *MockIFeedbackService_GetFeedbacksByConferenceID_Call) Return(_a0 []dto.FeedbackResponse, _a1 dto.LazyLoadResponse, _a2 error) *MockIFeedbackService_GetFeedbacksByConferenceID_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockIFeedbackService_GetFeedbacksByConferenceID_Call) RunAndReturn(run func(context.Context, uuid.UUID, dto.LazyLoadQuery) ([]dto.FeedbackResponse, dto.LazyLoadResponse, error)) *MockIFeedbackService_GetFeedbacksByConferenceID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIFeedbackService creates a new instance of MockIFeedbackService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIFeedbackService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIFeedbackService {
	mock := &MockIFeedbackService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
